---
# https://yamllint.readthedocs.io/en/stable/rules.html

ignore: |
  .copier-answers.yml

yaml-files:
  - "*.yaml"
  - "*.yml"

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
  comments:
    level: warning
    require-starting-space: true
    min-spaces-from-content: 1
  comments-indentation: disable
  document-end:
    present: true
  document-start:
    present: true
  empty-lines:
    level: warning
    max: 2
    max-start: 0
    max-end: 1
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: consistent
    indent-sequences: true
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  # Use UNIX new line characters `\n` instead of DOS new line characters `\r\n`
  new-lines:
    type: unix
  octal-values: disable
  quoted-strings:
    quote-type: double
    required: only-when-needed
  trailing-spaces: enable
  truthy:
    allowed-values: ["true", "false"]

...
